### ISSUE TITLE
Documentacion de la App Android con Javadoc

### ISSUE THREAD

**Issue by JArandaIzquierdo** [CrazyMind-Grx/VirtualBoard#39]

**Comment by JavideBaza** [comment]
me encargo de documentar esto! no problemo

**Comment by JavideBaza** [comment]
modificando y documentando el mainActivity

**Comment by JavideBaza** [comment]
Gente, ya esta la el javadoc terminado, echadle un ojo a ver que os parece

**Comment by marquina91** [comment]
Esta bien,pero algunos returns no los has puesto(que es lo más importante), mañana los completo que documentare yo la aplicación con uso de socket

**Comment by marquina91** [comment]
acabo de añadir los return que faltaban ya, mira ver si te gusta!

**Comment by angeljcc** [comment]
referenciad cada cosa que hagas por aqui en el commit @marquina91 @JavideBaza
